=== cedricrey/xNotes/src/dtd/xnotes.dtd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!ELEMENT notebook (note*, section*)>
  <!ELEMENT section (note*)>
    <!ELEMENT note (#PCDATA)>
    
<!ATTLIST notebook 
	id CDATA #IMPLIED
	title CDATA #REQUIRED
	modified CDATA #IMPLIED
	created CDATA #IMPLIED>
<!ATTLIST section
	id CDATA #IMPLIED
	title CDATA #REQUIRED
	modified CDATA #IMPLIED
	created CDATA #IMPLIED>
<!ATTLIST note 
	type (html|link|video) #IMPLIED
	title CDATA #IMPLIED
	modified CDATA #IMPLIED
	created CDATA #IMPLIED
	viewstate (open|closed) #IMPLIED>

=== cedricrey/xNotes/users/crey/notebooks/a.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE notebook PUBLIC "-//W3C//DTD XML 1.00//EN" "../../../dtd/xnotes.dtd">
<notebook title="a" modified="2013-08-28T11:24:53+02:00">
  <section id="section_463" title="tete   " modified="2013-08-28T11:24:53+02:00">
    <note id="note_540" modified="2013-08-28T11:18:50+02:00" viewstate="open"><![CDATA[rezerezrzr rey iiiii dsq]]></note>
    <note id="note_539" modified="2013-08-28T11:24:53+02:00" viewstate="open"><![CDATA[rehjk sfdsfds fff]]></note>
    <note id="note_538" modified="2013-08-28T10:44:35+02:00" viewstate="open"><![CDATA[rererre fdsdf hj]]></note>
    <note id="note_491" viewstate="open"><![CDATA[<div>&lt;blockquote class=\"twitter-tweet\"&gt;&lt;p&gt;Give TweetDeck the ol&amp;#39; college try. I think because it shows so much it encourages to keep it closed most of the time and catch up quickly.&lt;/p&gt;&amp;mdash; Chris Coyier (@chriscoyier) &lt;a href=\"https://twitter.com/chriscoyier/statuses/355303602119639040\"&gt;July 11, 2013&lt;/a&gt;&lt;/blockquote&gt;</div><div>&lt;script async src=\"//platform.twitter.com/widgets.js\" charset=\"utf-8\"&gt;&lt;/script&gt;</div>]]></note>
    <note id="note_606" created="2013-08-28T10:42:39+02:00" modified="2013-08-28T10:42:50+02:00" type="html" viewstate="open"><![CDATA[Ezaezaec hhkhj]]></note>
  </section>
  <section id="section_464" title="blabla " modified="2013-08-21T19:07:14+02:00">
    <note id="note_541" viewstate="open"><![CDATA[dsfdsf]]></note>
    <note id="note_546" viewstate="open"><![CDATA[rezzer]]></note>
    <note id="note_545" viewstate="open"><![CDATA[ttttttttt]]></note>
    <note id="note_544" viewstate="open"><![CDATA[]]></note>
    <note id="note_543" viewstate="open"><![CDATA[fdsfsqsdfqqsffdsqfsq]]></note>
    <note id="note_542" viewstate="open"><![CDATA[fdsfdsfdsf]]></note>
    <note id="note_492" viewstate="closed"><![CDATA[fdsfdsfds fdsf dsf]]></note>
    <note id="note_493" viewstate="open"><![CDATA[ddsqdsq fsq dsqd sq dsq dq dsq dsq]]></note>
    <note id="note_494" viewstate="open"><![CDATA[dsqdsqdsqdsq]]></note>
    <note id="note_495" viewstate="open"><![CDATA[fdsdfs dsf&nbsp;]]></note>
    <note id="note_496" viewstate="open"><![CDATA[sdf fds fds<div><br></div>]]></note>
    <note id="note_497" viewstate="open"><![CDATA[sdqsdsqdqsd&nbsp;]]></note>
    <note id="note_547" viewstate="open"><![CDATA[tteerrere]]></note>
  </section>
</notebook>

=== cedricrey/xNotes/Recette_de_cuisine.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE notebook PUBLIC "-//W3C//DTD XML 1.00//EN" "xnotes.dtd">
<notebook title="Recette de cuisine">
  <section title="b">
    <note><![CDATA[<p>bonjour, ceci est un test</p>]]></note>
    <note><![CDATA[]]></note>
  </section>
  <section title="c">
    <note><![CDATA[<p>Cd</p>]]></note>
    <note><![CDATA[<p>Ca</p>]]></note>
    <note><![CDATA[Cb]]></note>
    <note><![CDATA[tete]]></note>
    <note><![CDATA[kikou mon coco]]></note>
    <note><![CDATA[Cc]]></note>
  </section>
  <section title="a">
    <note><![CDATA[Ac]]></note>
    <note><![CDATA[Aa]]></note>
    <note><![CDATA[Ab]]></note>
  </section>
  <section title="d">
    <note><![CDATA[turlute]]></note>
    <note><![CDATA[turlute]]></note>
  </section>
</notebook>
